project_id = "hokiuavxyoymcenqlvly"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-operator]
    verify_jwt = false
  [functions.create-tenant-user]
    verify_jwt = false
  [functions.delete-tenant-user]
    verify_jwt = false
  [functions.request-password-reset]
    verify_jwt = false
  [functions.ocr-stamp]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-welcome-email]
    verify_jwt = false
