project_id = "hokiuavxyoymcenqlvly"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-operator]
    verify_jwt = false
  [functions.create-tenant-user]
    verify_jwt = false
  [functions.delete-tenant-user]
    verify_jwt = false
  [functions.request-password-reset]
    verify_jwt = false
  [functions.ocr-stamp]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-welcome-email]
    verify_jwt = false
  [functions.get-email-log]
    verify_jwt = false
  [functions.log-login]
    verify_jwt = false
  [functions.process-scheduled-type-changes]
    verify_jwt = false
  [functions.notify-destruction-due]
    verify_jwt = false
  [functions.send-new-mail-email]
    verify_jwt = false
  [functions.notify-scan-request]
    verify_jwt = false
